version: '2.2'
services:
  oscar:
    image: oscar-autostart
    container_name: oscar_ubuntu
    restart: unless-stopped
    ports:
      - 5800:5800
      - 5900:5900
    volumes:
      - ./oscar-data:/config/Documents/OSCAR_Data
      - ./SDCARD:/config/SDCARD
    environment:
      TZ: "America/Chicago"
